### ISSUE TITLE
Chikou Span (Ichimoku Cloud Lagging Price)

### ISSUE THREAD

**Issue by MichealReed** [freqtrade/technical#12]
I plan to raise this as a different issue in the freqtrade repo, but the way the chikou span is implemented allows the backtesting engine to look at future data. Chikou is only supposed to be a visual indicator for plotting the current price 26-30 ticks back on the chart.

**Comment by xmatthias** [comment]
We've since added a warning noting to not use chikou_span for backtesting to the method's dostring.

https://github.com/freqtrade/technical/blob/9924ee42a46811ce33bd46ab760d00a6cd0e48b0/technical/indicators.py#L247-L260

The main problem with ichimoku cloud is that it's a visual indicator (designed for people to look at charts) - and not necessarily for algo trading. While i CAN be used for that - it needs to be done in a carefull manner.

I don't think we should remove this line, as it IS part of ichimoku cloud - and can be quite usefull when used in plotting.

Hope this makes sense.
