### ISSUE TITLE
resample_to_interval date shifted 

### ISSUE THREAD

**Issue by ykoretskyi** [freqtrade/technical#271]
Hi, I am trying to implement resample_to_interval into my strategy, but faced with an issue (as for me):
![Screenshot 2022-06-23 at 10 46 26](https://user-images.githubusercontent.com/71146654/175258041-4ee0ad92-7de4-454d-b694-f31ddaf6849b.png)

as you can see on the screenshot date merged incorrectly, I assume that the date for 1m timeframe should be the same as for 5m dataframe, so it should be something like that:
![Screenshot 2022-06-23 at 11 57 50](https://user-images.githubusercontent.com/71146654/175260057-4041f4c6-09ed-45b3-942d-a3dee84f85a1.png)

if it is wrong could you please explain to me why, and if it's true how can I fix it?

**Comment by xmatthias** [comment]
It's correct as is (but it's often misunderstood - and most likely a huge cause of bugs, too.

since all date columns are candle open columns - the proper merge for a :40 candle (goes from :40-:45) is the :44 candle (going from :44-:45).

Your "how it should be" uses a 5m candle (from :40-:45) at :41 (when then :40-:41 candle is finished) before the candle is complete. The only value you can reliably use from this candle at this point in time is the candle's open - which is usually not what you need (and which freqtrade won't give you in live mode, either).

For a more detailed explanation, please refer to this  answer i gave a few weeks ago https://github.com/freqtrade/technical/issues/268#issuecomment-1146753500
