### ISSUE TITLE
Pandas warning when setting fillna(0) on RMI calc

### ISSUE THREAD

**Issue by stash86** [freqtrade/technical#395]
This line will trigger pandas warning https://github.com/freqtrade/technical/blob/419268923965a53a6464aa9b0129b3de16d83303/technical/indicators/indicators.py#L965

```
/home/ftuser/.local/lib/python3.11/site-packages/technical/indicators/indicators.py:966: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with datetime64[ns, UTC], please explicitly cast to a compatible dtype first.
```

**Comment by xmatthias** [comment]
in what circumstance?

i've just tested that, and it doesn't raise that warning (pandas 2.1.4, a freshly loaded dataframe).

the only instance i can imagine this to happen if you've somehow got a date-column with missing dates in the dataframe (not the actual `['date']` column) ... but that'll probably mean a different error / problem prior to this

now a fix to this is simple - there's no real reason to apply the fillna to the whole dataframe ... but i think the actual CAUSE is one that's not dependent on this function.

**Comment by stash86** [comment]
It was another user who got the error. I haven't test it myself.
